### PR TITLE
Add "Target TTL"

### PR DESCRIPTION
**Pull request by MrBrikster**
Some users need it. Please, accept pull request!

### CODE REVIEW

**Comment by luca020400** [comment]
Need it for?

**Comment by MrBrikster** [comment]
We're from Russia... And... With "target ttl" a lot of users bypass our carriers' mobile network limitations.
Now we have to build custom kernel, unlock bootloader and flash it. 
It will be wonderful, if "Target TTL" will be included at stock kernel.

**Comment by luca020400** [comment]
That's a good reason for it not being included on their end. Thanks for clarifying

**Comment by MrBrikster** [comment]
Excuse me. I realized that it was a bad idea...

**Pull request closed without merging**
